{
 "title": "Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "SELECT host FROM hosts" },
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT name FROM projects WHERE host IN (${host:singlequote})"
   },
   {
    "name": "commit_id",
    "label": "Commit",
    "query": "SELECT DISTINCT commit_id FROM pipelines WHERE host IN (${host:singlequote}) AND project_name IN (${project:singlequote})"
   },
   {
    "name": "pipeline",
    "label": "Pipelines",
    "query": "SELECT id FROM pipelines WHERE host IN (${host:singlequote}) AND project_name IN (${project:singlequote}) AND commit_id IN (${commit_id:singlequote}) ORDER BY finished_at DESC LIMIT 50"
   },
   { "name": "kwhprice", "label": "Price per kWh", "query": "0.2847" }
  ]
 },
 "panels": [
  { "title": "General stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pipelines Executed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM pipelines WHERE host IN (${host:singlequote})"
    }
   ]
  },
  {
   "title": "Average Pipeline Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(EXTRACT(epoch FROM (finished_at - started_at))) / 60 AS avg_duration FROM pipelines WHERE host IN (${host:singlequote})"
    }
   ]
  },
  {
   "title": "Average Pipeline Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(consumption) / 1000000 AS avg_duration FROM pipelines WHERE host IN (${host:singlequote})"
    }
   ]
  },
  {
   "title": "Pipeline consumption per commit ID",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT AVG(consumption)/1000000 as consumption, LEFT(commit_id, 8) as commit_id FROM pipelines WHERE host IN (${host:singlequote}) GROUP BY commit_id"
    }
   ]
  },
  {
   "title": "Pipelines consumption in kJ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "rawSql": "SELECT id, (consumption/1000000) as consumption FROM pipelines WHERE host IN (${host:singlequote}) AND id IN (${pipeline:raw}) ORDER BY finished_at DESC LIMIT 20"
    }
   ]
  },
  {
   "title": "Energy consumption per day across all hosts and projects",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT SUM(consumption)/1000000 as consumption, DATE(started_at) as date FROM pipelines GROUP BY DATE(started_at)"
    }
   ]
  },
  {
   "title": "Energy consumption equivalent to boiling litres of water",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(consumption)/1000000/3600/93 as cost, host FROM pipelines GROUP BY host"
    }
   ]
  },
  {
   "title": "All-time cost in € for all pipelines per host",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(consumption)/1000000/3600000*${kwhprice:raw} as cost, host FROM pipelines GROUP BY host"
    }
   ]
  },
  { "title": "Pipeline $pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "pipeline" },
  {
   "title": "Consumption in kJ for pipeline $pipeline",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT (consumption_rate.consumption/1000000) as value, consumption_rate.time, stages.name as stage FROM consumption_rate LEFT JOIN stages ON consumption_rate.pipeline_id = stages.pipeline_id WHERE consumption_rate.time BETWEEN stages.started_at AND stages.finished_at AND consumption_rate.pipeline_id = $pipeline AND consumption_rate.host = '$host' ORDER BY time"
    }
   ]
  },
  {
   "title": "Consumption per stage",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "rawSql": "SELECT name, consumption/1000000 FROM stages WHERE pipeline_id = $pipeline AND name = 'lint' AND host = '$host'"
    },
    {
     "rawSql": "SELECT name, consumption/1000000 FROM stages WHERE pipeline_id = $pipeline AND name = 'test' AND host = '$host'"
    },
    {
     "rawSql": "SELECT name, consumption/1000000 FROM stages WHERE pipeline_id = $pipeline AND name = 'deploy' AND host = '$host'"
    }
   ]
  },
  {
   "title": "Pipeline jobs",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT name, stage, EXTRACT(epoch FROM (finished_at - started_at)) AS duration, status FROM jobs WHERE pipeline_id = $pipeline AND host = '$host' ORDER BY stage, name"
    }
   ]
  }
 ]
}