version: '3.2'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - TZ=Europe/Luxembourg
      - PGTZ=Europe/Luxembourg
    networks:
      - monitoring-network

  grafana:
    build:
      context: ./grafana
    depends_on:
      - postgres
    ports:
      - ${GRAFANA_PORT}:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/dashboard.json
    networks:
      - monitoring-network

volumes:
  postgres-data:


networks:
  monitoring-network:
    driver: bridge
